* Security
- XSS: The message from the greeting service (even though this is not necessary) as well as the users name are sanitized
- self.new(h(message))
- self.name = sanitize(self.name)
- In theory sanitizing either one of these two would be enough, but since we pass the name to the client as well, we should do both
- JWT had a security bug where specifying the algo none would cause it to accept bad tokens, ruby doesn't allow that
  - https://github.com/jwt/ruby-jwt/issues/75
- I'm use HS256 default JWT tokens with shared keys.
- For more security we can rotate the shared keys and store them in Vault rather than config files
- There's no TLS between the services, so someone could MITM the go greeting
 service
* Build & Run
* Architecture
** Tag v1.0
*** Rails Web
    - devise login
    - react + apollo frontend
    - graphql API
    - synchronous grpc call. asynchronous call in fiber would be nice, but then we would need to have a push to the client
*** Greeting API
   - grpc go greeting service. responds with Hello, + Name.
     The name is stored in the JWT
   - (I could also just use a JSON Api)
*** Deployment
* Security
** v1 Shared Secret
*** Mitigation
    Rotate shared secret, and distribute it with vault
** Pub Key
- Either there is a pub key store somewhere
- Or apps are deployed with each others pub keys - this is an issue
** GDPR Why google analytics?
Cause I want to know when you check out the page

* Install
** Ruby on Rails
This application requires:

- Ruby 2.4.2
- Rails 5.2.0

Learn more about [Installing Rails](http://railsapps.github.io/installing-rails.html).
** Other dependencies
- Go
- Node.js + npm (I guess this is a security issue all by itself)

** Preparations
We need to make sure the go grpc tools are available. And the ruby and go protobuf services are generated.
#+BEGIN_SRC sh
  ./prep.sh
  ./gen.sh  # this will also set the correct GOPATH and build the greeter
  (cd frontend ; yarn)
  (cd backend ; bundle install)
#+END_SRC

** Launch
Launching the services happens through foreman or docker.
#+BEGIN_SRC sh
  (cd backend ; foreman start)
#+END_SRC
* Todo
  - [X] set static shared key
  - [X] create ruby greeter client
  - [X] add JWT to go server
  - [ ] ansible deployment
  - [ ] add expiration on JWT token
  - [ ] Move const config from greeter_server to config files
  - [ ] add docker compose
  - [ ] javascript e2e testing
  - [ ] add TLS for service communication
  - [ ] add openid_connect and auth proxy
  - [ ] add something like linkerd for service communication
