---
- hosts: all
  pre_tasks:
    # - name: upgrade packages
    #   apt: upgrade=yes update_cache=yes cache_valid_time=300
    - apt: name=git state=present
  roles:
    - rvm
    - nodejs
    - nginx
    - golang
    - postgresql
