# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "greeter.HelloRequest" do
  end
  add_message "greeter.HelloReply" do
    optional :message, :string, 1
  end
end

module Greeter
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.HelloReply").msgclass
end
